### PR TITLE
Constrain numpy / update dependencies

### PR DESCRIPTION
**Pull request by kaitj**
Since the last PR that was merged, NumPy released 2.0. To maintain current functionality, I am suggesting we constrain `numpy<2.0`. We could upgrade this and update the methods called as needed, but with the current constraints on pandas, other issues arise (I think pandas 2.3.0+ is compatible with the new version of numpy). Was there a reason pandas was constrained - I am assuming maybe something with the pyarrow dependency that was introduced after?

This should fix the new occuring errors in the unit tests.

Additionally, updated the requirements.txt to use `bids2table==0.1.0`, which introduced the `with_meta` argument that is being used.

### CODE REVIEW

**Comment by nx10** [comment]
Constraining pandas was probably done for bids2table but I fixed that a while ago, I think it would be worth testing if everything works with the latest versions and then relax requirements

**Comment by kaitj** [comment]
> Constraining pandas was probably done for bids2table but I fixed that a while ago, I think it would be worth testing if everything works with the latest versions and then relax requirements

Cool - just tried removing the constraints and all the tests are still passing with `pandas=2.2.x` and `numpy==2.x.x` I've updated the "requirements.txt" file again just to reflect these updated versions used.

**Comment by clane9** [comment]
So it seems that since the tests pass, we don't need to constrain versions after all in the pyproject.toml?

Updating dependencies in the requirements.txt is fine with me.

**Comment by kaitj** [comment]
Looks that way. There shouldn't be any constraints in the general dependencies of the pyproject.toml unless I missed something.

**Pull request merged**
